Create endicia package
slingr-stack/endicia-package pull request #2
Opened 2023-12-28 15:51 UTC by agreggio-slingr

Pull-request for issue #15473 created by @agreggio-slingr 

## What it does?

Create endicia package

## How to test it?

You can install the following test [package](git@github.com:slingr-stack/endicia-package-test.git) with the following credentials.

Client ID: zGNzowNmPCPPTqmKfjSEPplfnW133rwZ
Client Secret: GPX_PTHFBolg5WH5U91sX-PiDsI4QbJDjOit-T2FhcqDmmU2rgDlvACWdhsphcfY
Code Verifier : 7f410047e678b110982e42c1c9489e5a365957407e72552da8e68afe

A. Test Environment Username: slingr-01
B. Test Environment Password: December2023!
```
var response = pkg.endicia.api.get('/balance')
log(JSON.stringify(response))
```

## Implementation notes

N/A

2024-01-02 13:11 UTC, pasaperez-slingr commented on README.md
> +You can make `GET`,`PUT`,`PATCH`,`DELETE` requests to the [endicia API](API_URL_HERE) like this:
Replace the API_URL_HERE by the link to documentation.

2024-01-02 13:12 UTC, pasaperez-slingr commented on README.md
> +var response = pkg.endicia.api.get('/path3')
Review this paths, add at least a couple, for example the same path witch you test in this PR.

2024-01-02 13:12 UTC, pasaperez-slingr commented on README.md
>  * HTTP Service (Latest Version)
```suggestion
* HTTP Service (v1.3.7 Version)
```

2024-01-02 13:18 UTC, pasaperez-slingr requested changes

2024-01-02 13:18 UTC, pasaperez-slingr commented on flowSteps/apiCallEndicia/step.js
> +	const result = {};
```suggestion
	var result = {};
```

2024-01-02 13:18 UTC, pasaperez-slingr commented on flowSteps/apiCallEndicia/step.js
> +	let key;
```suggestion
	var key;
```

2024-01-02 13:18 UTC, pasaperez-slingr commented on flowSteps/apiCallEndicia/step.js
> +exports.callbackTest = function () {
You can remove this call

2024-01-02 13:18 UTC, pasaperez-slingr commented on package.json
>              "type": "uiService",
You don't use this uiService

2024-01-02 13:19 UTC, pasaperez-work commented
#approve

2024-01-03 18:06 UTC, merged

2024-03-18 19:45 UTC, pasaperez-slingr commented
Retested on Test Packages of tarzan, the extenal system or the credentials could be expired.